/**
 * ============================================================================
 * PERSONALIZED RECOMMENDATIONS - Practical Example for Front-End Developers
 * ============================================================================
 * 
 * PROBLEM:
 * Front-end developers need to provide personalized recommendations without:
 * - Complex server-side recommendation engines
 * - Sending user behavior data to external services (privacy concerns)
 * - High latency from server round-trips
 * - Expensive recommendation APIs
 * - Losing personalization when offline
 * 
 * SOLUTION:
 * Use AsterMind ELM to create an on-device recommendation system that:
 * - Learns from user interactions in real-time
 * - Works entirely client-side (privacy-first)
 * - Provides instant recommendations (<10ms)
 * - Adapts as user behavior changes
 * - Works offline
 * 
 * HOW IT WORKS:
 * 
 *     User Interactions
 *         |
 *         v
 *     [Build User Profile] --> Embedding Vector
 *         |
 *         v
 *     [Compare with Items] --> Similarity Scores
 *         |
 *         v
 *     [Rank & Filter] --> Top Recommendations
 * 
 * ARCHITECTURE DIAGRAM:
 * 
 *     ┌──────────────┐
 *     │ User Clicks  │
 *     │  on Items   │
 *     └──────┬───────┘
 *            │
 *            v
 *     ┌──────────────┐      ┌─────────────┐
 *     │ Build User   │─────>│ User Profile│
 *     │ Profile      │      │ Embedding   │
 *     └──────────────┘      └──────┬──────┘
 *                                   │
 *                                   v
 *                          ┌─────────────────┐
 *                          │  Item Embeddings│
 *                          │  (All Items)    │
 *                          └────────┬────────┘
 *                                   │
 *                                   v
 *                          ┌─────────────────┐
 *                          │  Cosine         │
 *                          │  Similarity     │
 *                          └────────┬────────┘
 *                                   │
 *                                   v
 *                          ┌─────────────────┐
 *                          │  Top K          │
 *                          │  Recommendations│
 *                          └─────────────────┘
 * 
 * USER PROFILE:
 * The user profile is built from embeddings of items they've interacted with.
 * We average the embeddings of liked items to create a user preference vector.
 * 
 * ITEM EMBEDDINGS:
 * Each item has an embedding vector based on its features (category, tags, etc.).
 * These embeddings are generated using an ELM encoder trained on item features.
 * 
 * RECOMMENDATIONS:
 * Recommendations are generated by finding items with embeddings similar to
 * the user profile embedding using cosine similarity.
 * 
 * USAGE:
 * 1. Initialize item embeddings (one-time setup)
 * 2. Track user interactions (clicks, likes, views)
 * 3. Build user profile from interactions
 * 4. Generate recommendations based on similarity
 * 5. Update recommendations as user interacts more
 * 
 * PERFORMANCE:
 * - Initialization: ~100-500ms for item embeddings
 * - Recommendation generation: <10ms
 * - Memory: ~1-5MB for typical item catalogs
 * 
 * ============================================================================
 */

// © 2025 AsterMind LLC – All Rights Reserved.
// Patent Pending US 63/897,713

const { ELM, EmbeddingStore, UniversalEncoder } = window.astermind;

// ============================================================================
// SAMPLE ITEM DATA
// ============================================================================

const ITEMS = [
    { id: 1, title: "Action Movie", category: "movies", tags: ["action", "thriller", "adventure"] },
    { id: 2, title: "Comedy Show", category: "tv", tags: ["comedy", "funny", "entertainment"] },
    { id: 3, title: "Sci-Fi Book", category: "books", tags: ["sci-fi", "fiction", "space"] },
    { id: 4, title: "Romance Novel", category: "books", tags: ["romance", "drama", "love"] },
    { id: 5, title: "Horror Film", category: "movies", tags: ["horror", "scary", "thriller"] },
    { id: 6, title: "Documentary", category: "movies", tags: ["documentary", "educational", "real"] },
    { id: 7, title: "Fantasy Book", category: "books", tags: ["fantasy", "magic", "adventure"] },
    { id: 8, title: "Drama Series", category: "tv", tags: ["drama", "serious", "emotional"] },
    { id: 9, title: "Mystery Novel", category: "books", tags: ["mystery", "crime", "suspense"] },
    { id: 10, title: "Anime Series", category: "tv", tags: ["anime", "animation", "japanese"] },
    { id: 11, title: "Thriller Movie", category: "movies", tags: ["thriller", "suspense", "action"] },
    { id: 12, title: "Biography", category: "books", tags: ["biography", "non-fiction", "real"] },
    { id: 13, title: "Comedy Movie", category: "movies", tags: ["comedy", "funny", "entertainment"] },
    { id: 14, title: "Romance Series", category: "tv", tags: ["romance", "drama", "love"] },
    { id: 15, title: "Adventure Book", category: "books", tags: ["adventure", "action", "journey"] },
    { id: 16, title: "Crime Drama", category: "tv", tags: ["crime", "drama", "suspense"] },
    { id: 17, title: "Superhero Movie", category: "movies", tags: ["superhero", "action", "comic"] },
    { id: 18, title: "Historical Fiction", category: "books", tags: ["historical", "fiction", "past"] },
    { id: 19, title: "Reality Show", category: "tv", tags: ["reality", "entertainment", "real"] },
    { id: 20, title: "Musical Film", category: "movies", tags: ["musical", "music", "entertainment"] },
];

// ============================================================================
// STATE MANAGEMENT
// ============================================================================

let itemEncoder = null;
let itemEmbeddingStore = null;
let userInteractions = {
    viewed: new Set(), // Items the user has viewed
    liked: new Set(),  // Items the user has liked
};
let userProfileEmbedding = null;
let isReady = false;

// ============================================================================
// INITIALIZATION
// ============================================================================

/**
 * Initialize item embeddings
 * Creates embeddings for all items based on their features
 */
async function initializeItemEmbeddings() {
    console.log('🔧 Initializing item embeddings...');
    
    // Create ELM encoder for items
    // Train on classification task, then use hidden layer as embeddings
    // Let ELM create its own encoder to ensure consistency
    itemEncoder = new ELM({
        categories: ITEMS.map((_, i) => `item-${i}`), // Each item as a category
        hiddenUnits: 128,
        maxLen: 50,
        useTokenizer: true, // Enable text mode
        charSet: 'abcdefghijklmnopqrstuvwxyz0123456789 -',
        tokenizerDelimiter: /\s+/,
        activation: 'relu',
        weightInit: 'xavier',
        ridgeLambda: 0.01,
    });
    
    // Get ELM's internal encoder - this is the one that will be used for embeddings
    const textEncoder = itemEncoder['encoder'];
    if (!textEncoder) {
        throw new Error('Encoder not initialized');
    }
    
    // Get the expected vector size
    const expectedVectorSize = textEncoder.getVectorSize();
    console.log(`📏 Expected vector size: ${expectedVectorSize} dimensions`);
    
    // Prepare training data
    // Use item features (title + category + tags) as training examples
    const trainingTexts = ITEMS.map(item => {
        const features = `${item.title} ${item.category} ${item.tags.join(' ')}`;
        return features.toLowerCase();
    });
    
    // Encode texts and create one-hot labels
    const X = [];
    const Y = [];
    
    // Helper to encode and ensure consistent size
    const encodeAndPad = (text) => {
        const vec = textEncoder.normalize(textEncoder.encode(text));
        // Ensure vector is exactly the expected size
        if (vec.length !== expectedVectorSize) {
            console.warn(`⚠️ Vector size mismatch: got ${vec.length}, expected ${expectedVectorSize}. Fixing...`);
            const fixed = vec.slice(0, expectedVectorSize);
            while (fixed.length < expectedVectorSize) {
                fixed.push(0);
            }
            return fixed;
        }
        return vec;
    };
    
    trainingTexts.forEach((text, i) => {
        X.push(encodeAndPad(text));
        Y.push(itemEncoder.oneHot(ITEMS.length, i)); // Each item is its own category
    });
    
    // Verify all vectors have consistent size
    const firstSize = X[0]?.length;
    if (!firstSize || firstSize !== expectedVectorSize) {
        throw new Error(`Vector size mismatch: first vector is ${firstSize}, expected ${expectedVectorSize}`);
    }
    
    const inconsistent = X.find((v, i) => v.length !== firstSize);
    if (inconsistent) {
        const badIndex = X.findIndex(v => v.length !== firstSize);
        throw new Error(`Vector ${badIndex} has size ${X[badIndex].length}, expected ${firstSize}`);
    }
    
    console.log(`📚 Training encoder on ${X.length} items (all vectors: ${firstSize} dimensions)...`);
    const startTime = performance.now();
    
    itemEncoder.trainFromData(X, Y);
    
    const trainTime = performance.now() - startTime;
    console.log(`✅ Training complete in ${trainTime.toFixed(2)}ms`);
    
    // Build embedding store for all items
    buildItemEmbeddingStore();
    
    isReady = true;
    console.log('🚀 Recommendation system ready!');
}

/**
 * Build the embedding store with all item embeddings
 */
function buildItemEmbeddingStore() {
    console.log('📦 Building item embedding store...');
    
    itemEmbeddingStore = new EmbeddingStore(128, {
        capacity: 1000,
        storeUnit: true, // Normalize for cosine similarity
    });
    
    // Get encoder and expected vector size
    const textEncoder = itemEncoder['encoder'];
    if (!textEncoder) {
        throw new Error('Encoder not initialized');
    }
    
    const expectedVectorSize = textEncoder.getVectorSize();
    
    // Helper to encode and ensure consistent size
    const encodeAndPad = (text) => {
        const vec = textEncoder.normalize(textEncoder.encode(text.toLowerCase()));
        // Ensure vector is exactly the expected size
        if (vec.length !== expectedVectorSize) {
            console.warn(`⚠️ Vector size mismatch for "${text.substring(0, 30)}...": got ${vec.length}, expected ${expectedVectorSize}. Fixing...`);
            const fixed = vec.slice(0, expectedVectorSize);
            while (fixed.length < expectedVectorSize) {
                fixed.push(0);
            }
            return fixed;
        }
        return vec;
    };
    
    // Generate and store embeddings for all items
    ITEMS.forEach(item => {
        const features = `${item.title} ${item.category} ${item.tags.join(' ')}`;
        const vec = encodeAndPad(features);
        
        // Get embedding from ELM
        const embeddingBatch = itemEncoder.getEmbedding([vec]);
        
        // Ensure we have a valid embedding
        if (!Array.isArray(embeddingBatch) || !embeddingBatch[0] || !Array.isArray(embeddingBatch[0])) {
            console.error(`Failed to get embedding for item ${item.id}`);
            return;
        }
        
        const embedding = Array.from(embeddingBatch[0]); // Ensure it's a plain array
        
        // Verify embedding size matches store dimension
        if (embedding.length !== 128) {
            console.warn(`⚠️ Embedding size ${embedding.length} doesn't match store dimension 128. Padding/truncating...`);
            const fixed = embedding.slice(0, 128);
            while (fixed.length < 128) {
                fixed.push(0);
            }
            itemEmbeddingStore.add({
                id: `item-${item.id}`,
                vec: fixed,
                meta: item,
            });
        } else {
            itemEmbeddingStore.add({
                id: `item-${item.id}`,
                vec: embedding,
                meta: item,
            });
        }
    });
    
    console.log(`✅ Stored ${itemEmbeddingStore.size()} item embeddings`);
}

/**
 * Build user profile embedding from interactions
 * Averages embeddings of liked items to create user preference vector
 */
function buildUserProfile() {
    if (userInteractions.liked.size === 0) {
        userProfileEmbedding = null;
        return;
    }
    
    console.log('👤 Building user profile...');
    
    // Get embeddings of all liked items
    const likedItemIds = Array.from(userInteractions.liked);
    const likedEmbeddings = likedItemIds
        .map(id => {
            const itemId = `item-${id}`;
            const record = itemEmbeddingStore.get(itemId);
            // Use raw vector if available, otherwise use normalized vector
            return record ? (record.raw ? Array.from(record.raw) : Array.from(record.vec)) : null;
        })
        .filter(emb => emb !== null);
    
    if (likedEmbeddings.length === 0) {
        userProfileEmbedding = null;
        return;
    }
    
    // Average the embeddings to create user profile
    // This represents the user's preference vector
    const embeddingDim = likedEmbeddings[0].length;
    userProfileEmbedding = new Array(embeddingDim).fill(0);
    
    likedEmbeddings.forEach(embedding => {
        embedding.forEach((val, i) => {
            userProfileEmbedding[i] += val;
        });
    });
    
    // Average
    userProfileEmbedding = userProfileEmbedding.map(val => val / likedEmbeddings.length);
    
    // Normalize the profile vector
    const magnitude = Math.sqrt(
        userProfileEmbedding.reduce((sum, val) => sum + val * val, 0)
    );
    if (magnitude > 0) {
        userProfileEmbedding = userProfileEmbedding.map(val => val / magnitude);
    }
    
    console.log(`✅ User profile built from ${likedEmbeddings.length} liked items`);
}

/**
 * Generate recommendations based on user profile
 * @param {number} topK - Number of recommendations to return
 * @returns {Array} Array of recommended items with scores
 */
function generateRecommendations(topK = 6) {
    if (!isReady || !userProfileEmbedding) {
        return [];
    }
    
    // Get all items user hasn't interacted with
    const allItemIds = ITEMS.map(item => item.id);
    const unviewedItemIds = allItemIds.filter(
        id => !userInteractions.viewed.has(id) && !userInteractions.liked.has(id)
    );
    
    if (unviewedItemIds.length === 0) {
        return [];
    }
    
    // Find similar items using cosine similarity
    const recommendations = itemEmbeddingStore.query(
        userProfileEmbedding, // Query vector (first parameter)
        Math.min(topK * 2, itemEmbeddingStore.size()), // Get more candidates
        { metric: 'cosine' } // Options: Use cosine similarity
    );
    
    // Filter out items user has already interacted with
    const filtered = recommendations
        .filter(hit => {
            // Handle both cases: hit.meta.id might be a number or string
            let itemId;
            if (typeof hit.meta.id === 'number') {
                itemId = hit.meta.id;
            } else if (typeof hit.meta.id === 'string') {
                // If it's a string like "item-1", extract the number
                itemId = parseInt(hit.meta.id.replace('item-', ''));
            } else {
                // Fallback: try to get id from hit.id or hit.meta
                const idStr = hit.id || hit.meta?.id || '';
                itemId = parseInt(idStr.toString().replace('item-', ''));
            }
            
            // Skip if we couldn't parse a valid ID
            if (isNaN(itemId)) {
                console.warn('Could not parse item ID from:', hit);
                return false;
            }
            
            return !userInteractions.viewed.has(itemId) && !userInteractions.liked.has(itemId);
        })
        .slice(0, topK); // Take top K
    
    return filtered.map(hit => ({
        ...hit.meta,
        score: hit.score,
        reason: getRecommendationReason(hit.meta, hit.score),
    }));
}

/**
 * Get a human-readable reason for the recommendation
 */
function getRecommendationReason(item, score) {
    const percent = Math.round(score * 100);
    
    // Find common tags with liked items
    const likedItems = Array.from(userInteractions.liked)
        .map(id => ITEMS.find(item => item.id === id))
        .filter(Boolean);
    
    const likedTags = new Set();
    likedItems.forEach(item => {
        item.tags.forEach(tag => likedTags.add(tag));
    });
    
    const commonTags = item.tags.filter(tag => likedTags.has(tag));
    
    if (commonTags.length > 0) {
        return `Similar tags: ${commonTags.slice(0, 2).join(', ')}`;
    } else if (likedItems.length > 0) {
        const likedCategory = likedItems[0].category;
        if (item.category === likedCategory) {
            return `Same category: ${item.category}`;
        }
    }
    
    return `${percent}% match to your preferences`;
}

// ============================================================================
// RENDERING
// ============================================================================

/**
 * Render all items in the browse grid
 */
function renderItems() {
    const itemGrid = document.getElementById('itemGrid');
    itemGrid.innerHTML = '';
    
    ITEMS.forEach(item => {
        const card = document.createElement('div');
        card.className = 'item-card';
        
        // Mark if interacted
        if (userInteractions.liked.has(item.id)) {
            card.classList.add('interacted');
        }
        
        card.innerHTML = `
            <div class="item-title">${item.title}</div>
            <div class="item-category">${item.category}</div>
            <div class="item-tags">
                ${item.tags.map(tag => `<span class="item-tag">${tag}</span>`).join('')}
            </div>
        `;
        
        // Click handler
        card.addEventListener('click', () => {
            handleItemInteraction(item.id);
        });
        
        itemGrid.appendChild(card);
    });
}

/**
 * Render recommendations
 */
function renderRecommendations() {
    const recommendationGrid = document.getElementById('recommendationGrid');
    
    if (!userProfileEmbedding) {
        recommendationGrid.innerHTML = `
            <div style="padding: 2rem; text-align: center; color: #6b7280; grid-column: 1 / -1;">
                Like some items above to see personalized recommendations!
            </div>
        `;
        return;
    }
    
    const recommendations = generateRecommendations(6);
    
    if (recommendations.length === 0) {
        recommendationGrid.innerHTML = `
            <div style="padding: 2rem; text-align: center; color: #6b7280; grid-column: 1 / -1;">
                You've viewed all items! Try resetting to see recommendations again.
            </div>
        `;
        return;
    }
    
    recommendationGrid.innerHTML = '';
    
    recommendations.forEach(item => {
        const card = document.createElement('div');
        card.className = 'recommendation-card';
        
        const scorePercent = Math.round(item.score * 100);
        
        card.innerHTML = `
            <div class="recommendation-score">${scorePercent}% match</div>
            <div class="recommendation-title">${item.title}</div>
            <div class="recommendation-category">${item.category}</div>
            <div class="recommendation-reason">${item.reason}</div>
        `;
        
        recommendationGrid.appendChild(card);
    });
}

/**
 * Update statistics display
 */
function updateStats() {
    document.getElementById('viewedCount').textContent = userInteractions.viewed.size;
    document.getElementById('likedCount').textContent = userInteractions.liked.size;
    
    const recommendations = userProfileEmbedding ? generateRecommendations(6) : [];
    document.getElementById('recommendationCount').textContent = recommendations.length;
}

/**
 * Handle item interaction (click)
 */
function handleItemInteraction(itemId) {
    // Toggle like status
    if (userInteractions.liked.has(itemId)) {
        userInteractions.liked.delete(itemId);
    } else {
        userInteractions.liked.add(itemId);
    }
    
    // Always mark as viewed
    userInteractions.viewed.add(itemId);
    
    // Rebuild user profile
    buildUserProfile();
    
    // Update UI
    renderItems();
    renderRecommendations();
    updateStats();
    
    console.log(`📊 Interactions updated: ${userInteractions.liked.size} liked, ${userInteractions.viewed.size} viewed`);
}

/**
 * Reset all interactions
 */
window.resetInteractions = function() {
    if (confirm('Reset all interactions? This will clear your preferences.')) {
        userInteractions.viewed.clear();
        userInteractions.liked.clear();
        userProfileEmbedding = null;
        
        renderItems();
        renderRecommendations();
        updateStats();
        
        console.log('🔄 Interactions reset');
    }
};

// ============================================================================
// STARTUP
// ============================================================================

window.addEventListener('DOMContentLoaded', async () => {
    try {
        await initializeItemEmbeddings();
        renderItems();
        renderRecommendations();
        updateStats();
    } catch (error) {
        console.error('❌ Initialization error:', error);
        alert('Failed to initialize recommendation system: ' + error.message);
    }
});




